"""
Cream & Co. — Database Seed Data
==================================
Seeds the database with initial categories and the full product catalog.
Run this once after initializing the database.
"""

from slugify import slugify


# ---------------------------------------------------------------------------
# Categories
# ---------------------------------------------------------------------------
CATEGORIES = [
    {
        "name": "Specials",
        "slug": "specials",
        "description": "Our signature handcrafted treats and seasonal favorites",
        "image_url": "/specials.jpg",
        "display_order": 1,
    },
    {
        "name": "Combos",
        "slug": "combos",
        "description": "Perfect pairings at unbeatable value",
        "image_url": "/combos.jpg",
        "display_order": 2,
    },
    {
        "name": "Cakes",
        "slug": "cakes",
        "description": "Freshly baked celebration cakes for every occasion",
        "image_url": "/cakes.jpg",
        "display_order": 3,
    },
    {
        "name": "Tub Cakes",
        "slug": "tub-cakes",
        "description": "Rich, indulgent tub cakes loaded with premium toppings",
        "image_url": "/tub_cakes.jpg",
        "display_order": 4,
    },
]


# ---------------------------------------------------------------------------
# Products
# ---------------------------------------------------------------------------
PRODUCTS = [
    # ── Specials ──────────────────────────────────────────────────────────
    {
        "name": "Choco Lava",
        "slug": "choco-lava",
        "description": "Choco lava cake is a popular dessert known for its molten chocolate center. A warm, rich chocolate shell gives way to a flowing river of velvety chocolate inside.",
        "price": 120.0,
        "image_url": "/choco_lava.jpg",
        "category_slug": "specials",
        "is_veg": True,
        "is_bestseller": True,
        "weight_info": "",
    },
    {
        "name": "Chocolate Brownie",
        "slug": "chocolate-brownie",
        "description": "Chocolate brownies are a classic dessert. They are typically made with chocolate, butter, sugar, eggs, and flour, resulting in a dense, fudgy texture with an irresistible cocoa flavor.",
        "price": 100.0,
        "image_url": "/chocolate_brownie.jpg",
        "category_slug": "specials",
        "is_veg": True,
        "is_bestseller": True,
        "weight_info": "",
    },
    {
        "name": "Chocolate Doughnut",
        "slug": "chocolate-doughnut",
        "description": "Chocolate doughnut is a chocolaty, sweet and caramel like flavour. Its fried and glazed with rich chocolate coating that melts in your mouth.",
        "price": 60.0,
        "image_url": "/chocolate_doughnut.jpg",
        "category_slug": "specials",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "1 Piece",
    },
    {
        "name": "White Chocolate Doughnut",
        "slug": "white-chocolate-doughnut",
        "description": "White Chocolate Doughnut is a sweet and caramel like flavour. It is fried and glazed with premium white chocolate for a creamy, dreamy bite.",
        "price": 60.0,
        "image_url": "/white_chocolate_doughnut.jpg",
        "category_slug": "specials",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "1 Piece",
    },
    {
        "name": "Lotus Biscoff Cheesecake Pastry",
        "slug": "lotus-biscoff-cheesecake-pastry",
        "description": "A luxurious no-bake cheesecake with creamy Lotus Biscoff spread, crushed speculoos cookies, and a buttery biscuit base.",
        "price": 150.0,
        "image_url": "/lotus_biscoff.jpg",
        "category_slug": "specials",
        "is_veg": True,
        "is_bestseller": True,
        "weight_info": "",
    },
    {
        "name": "Nutella Cheesecake Pastry",
        "slug": "nutella-cheesecake-pastry",
        "description": "A velvety no-bake cheesecake swirled with rich Nutella hazelnut spread on a crisp biscuit base.",
        "price": 140.0,
        "image_url": "/nutella_cheesecake.jpg",
        "category_slug": "specials",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "",
    },
    {
        "name": "Pineapple Pastry",
        "slug": "pineapple-pastry",
        "description": "A delightful pastry in a form of mini cake, layered with fresh cream and sweet pineapple chunks.",
        "price": 80.0,
        "image_url": "/pineapple_pastry.jpg",
        "category_slug": "specials",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "",
    },
    {
        "name": "White Forest Pastry",
        "slug": "white-forest-pastry",
        "description": "A classic pastry in a form of mini cake, with fluffy vanilla sponge, white chocolate shavings, and cherry filling.",
        "price": 80.0,
        "image_url": "/white_forest_pastry.jpg",
        "category_slug": "specials",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "",
    },
    {
        "name": "Blueberry Cheesecake",
        "slug": "blueberry-cheesecake",
        "description": "A luscious no-bake cheesecake topped with a vibrant blueberry compote and a buttery crumb base.",
        "price": 150.0,
        "image_url": "/blueberry_cheesecake.jpg",
        "category_slug": "specials",
        "is_veg": True,
        "is_bestseller": True,
        "weight_info": "",
    },
    # ── Combos ────────────────────────────────────────────────────────────
    {
        "name": "Choco Lava with Chocolate Brownie",
        "slug": "choco-lava-chocolate-brownie-combo",
        "description": "The ultimate chocolate lovers' combo — our signature molten choco lava cake paired with a rich, fudgy chocolate brownie.",
        "price": 199.0,
        "image_url": "/combo_lava_brownie.jpg",
        "category_slug": "combos",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "",
    },
    {
        "name": "Chocolate Doughnut with Choco Lava Cake",
        "slug": "choco-doughnut-lava-combo",
        "description": "A heavenly pairing — a chocolate glazed doughnut alongside our warm molten choco lava cake.",
        "price": 169.0,
        "image_url": "/combo_doughnut_lava.jpg",
        "category_slug": "combos",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "",
    },
    {
        "name": "Choco Lava with White Chocolate Doughnut",
        "slug": "choco-lava-white-doughnut-combo",
        "description": "Best of both worlds — warm choco lava cake meets a creamy white chocolate glazed doughnut.",
        "price": 169.0,
        "image_url": "/combo_lava_white_doughnut.jpg",
        "category_slug": "combos",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "",
    },
    # ── Cakes ─────────────────────────────────────────────────────────────
    {
        "name": "Chocolate Cake",
        "slug": "chocolate-cake-500g",
        "description": "Savour the delight of a cream filled chocolate cake, a heavenly confection that combines rich layers of moist chocolate sponge with luscious chocolate cream frosting.",
        "price": 450.0,
        "image_url": "/chocolate_cake.jpg",
        "category_slug": "cakes",
        "is_veg": True,
        "is_bestseller": True,
        "weight_info": "500 g",
    },
    {
        "name": "White Forest Cake",
        "slug": "white-forest-cake-500g",
        "description": "Vanilla sponge with a delightful combination of cherries and white choco chips, topped with swirls of fresh cream.",
        "price": 450.0,
        "image_url": "/white_forest_cake.jpg",
        "category_slug": "cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "500 g",
    },
    {
        "name": "Butterscotch Cake",
        "slug": "butterscotch-cake-500g",
        "description": "This cake is a tempting combination of vanilla sponge, butterscotch chunks with delicious cream and a golden butterscotch sauce drizzle.",
        "price": 450.0,
        "image_url": "/butterscotch_cake.jpg",
        "category_slug": "cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "500 g",
    },
    {
        "name": "Pineapple Cake",
        "slug": "pineapple-cake-500g",
        "description": "Cake made with fresh cream, sweet pineapple filling and soft vanilla sponge layers — a tropical classic.",
        "price": 450.0,
        "image_url": "/pineapple_cake.jpg",
        "category_slug": "cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "500 g",
    },
    {
        "name": "Rasmalai Cake",
        "slug": "rasmalai-cake-500g",
        "description": "A fusion masterpiece combining the traditional rasmalai flavors with modern cake artistry — sponge soaked in cardamom-infused milk, topped with saffron cream.",
        "price": 550.0,
        "image_url": "/rasmalai_cake.jpg",
        "category_slug": "cakes",
        "is_veg": True,
        "is_bestseller": True,
        "weight_info": "500 g",
    },
    {
        "name": "Rabri Gulab Jamun Cake",
        "slug": "rabri-gulab-jamun-cake-500g",
        "description": "An indulgent fusion of rich rabri layers and soft gulab jamuns nestled between sponge cake — a dessert lover's dream.",
        "price": 550.0,
        "image_url": "/rabri_gulab_jamun_cake.jpg",
        "category_slug": "cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "500 g",
    },
    {
        "name": "Strawberry Cake",
        "slug": "strawberry-cake-500g",
        "description": "A fresh strawberry flavored cream cake with vibrant strawberry sponge, real berry pieces, and a cloud of strawberry-infused frosting.",
        "price": 450.0,
        "image_url": "/strawberry_cake.jpg",
        "category_slug": "cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "500 g",
    },
    {
        "name": "Butterfly Cake",
        "slug": "butterfly-cake-500g",
        "description": "A decorative butterfly-themed cake with colorful buttercream wings, vanilla sponge, and a whimsical design that's perfect for celebrations.",
        "price": 500.0,
        "image_url": "/butterfly_cake.jpg",
        "category_slug": "cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "500 g",
    },
    {
        "name": "Belgian Chocolate Cake",
        "slug": "belgian-chocolate-cake-500g",
        "description": "Made with premium dark Belgian chocolate — a decadent, intensely rich chocolate experience with a velvety ganache finish.",
        "price": 550.0,
        "image_url": "/belgian_chocolate_cake.jpg",
        "category_slug": "cakes",
        "is_veg": True,
        "is_bestseller": True,
        "weight_info": "500 g",
    },
    {
        "name": "Marble Cake",
        "slug": "marble-cake-500g",
        "description": "No cream cake, perfect for those who like dry cakes. Beautiful swirls of vanilla and chocolate batter baked to golden perfection.",
        "price": 400.0,
        "image_url": "/marble_cake.jpg",
        "category_slug": "cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "500 g",
    },
    # ── Tub Cakes ─────────────────────────────────────────────────────────
    {
        "name": "Kunafa Tub Cake",
        "slug": "kunafa-tub-cake",
        "description": "A delightful fusion of crispy golden kunafa layers, soft moist cake and soaked in sweet syrup — a Middle Eastern meets modern dessert experience.",
        "price": 250.0,
        "image_url": "/kunafa_tub_cake.jpg",
        "category_slug": "tub-cakes",
        "is_veg": True,
        "is_bestseller": True,
        "weight_info": "",
    },
    {
        "name": "Triple Chocolate Tub Cake",
        "slug": "triple-chocolate-tub-cake",
        "description": "Tub cake loaded with the trifecta of milk, dark, and white chocolate — three layers of pure chocolate bliss in every spoonful.",
        "price": 220.0,
        "image_url": "/triple_chocolate_tub.jpg",
        "category_slug": "tub-cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "",
    },
    {
        "name": "Cookie and Cream Tub Cake",
        "slug": "cookie-and-cream-tub-cake",
        "description": "Loaded with crushed Oreo cookies folded into velvety cream and moist cake — cookies and cream lovers' paradise.",
        "price": 220.0,
        "image_url": "/cookie_cream_tub.jpg",
        "category_slug": "tub-cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "",
    },
    {
        "name": "Belgian Chocolate Tub Cake",
        "slug": "belgian-chocolate-tub-cake",
        "description": "Loaded with premium Belgian chocolate chunks in a rich, indulgent tub cake that's pure dark chocolate heaven.",
        "price": 250.0,
        "image_url": "/belgian_chocolate_tub.jpg",
        "category_slug": "tub-cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "",
    },
    {
        "name": "Cadbury Crackle Tub Cake",
        "slug": "cadbury-crackle-tub-cake",
        "description": "If you love Cadbury Crackle chocolate you gonna love this tub cake too. Crunchy rice puffs coated in Cadbury chocolate layered with moist cake.",
        "price": 220.0,
        "image_url": "/cadbury_crackle_tub.jpg",
        "category_slug": "tub-cakes",
        "is_veg": True,
        "is_bestseller": False,
        "weight_info": "",
    },
]


def get_seed_categories() -> list[dict]:
    """Return the list of category seed data."""
    return CATEGORIES


def get_seed_products() -> list[dict]:
    """Return the list of product seed data."""
    return PRODUCTS
